[package]
name = "noline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.6"
staticvec = "0.11.1"
embedded-hal = {version = "0.2.6", optional = true}
nb = {version = "1.0.0", optional = true}

[features]
std = []
embedded = ["embedded-hal", "nb"]

[dev-dependencies]
embedded-hal = "0.2.6"
nb = "1.0.0"
