[package]
name = "noline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = {version = "0.5.6", default-features = false}
embedded-hal = {version = "0.2.6", optional = true}
nb = {version = "1.0.0", optional = true}
tokio = {version = "1.16.1", optional = true, features = ["io-util", "sync"]}

[features]
default = ["std", "tokio", "embedded"]
std = []
embedded = ["embedded-hal", "nb"]

[dev-dependencies]
